### PR TITLE
SDK and Flutter updates

### PR DESCRIPTION
**Pull request by jjrbfi**
Android SDK and Flutter updated to the latest version.

### CODE REVIEW

**Comment by matsp** [comment]
Thanks for the PR, can you also increase the beta and dev version?

**Comment by jjrbfi** [comment]
Done :)

All updated to last versions, and directory correction after uncompressed.

**Comment by matsp** [comment]
Please fill in the right dev and beta version in each file. Actually you just put the stable version in each file ;)

**Comment by jjrbfi** [comment]
Done :)

> Please fill in the right dev and beta version in each file. Actually you just put the stable version in each file ;)

Done :)

**Pull request merged**
